version: "3"

services:
  xmr:
    image: xmr-dev
    volumes:
     - ./:/opt/xmr
    ports:
     - "9506:9505"
     - "50001:50001"
    environment:
      XMR_DEBUG: "true"
      XMR_DEV_MODE: "false"